"""
Interface definition for ``Sampler`` objects.

This will be moved to ``codepyinterfaces`` the next time that package
is updated.
"""

import abc


class SamplerInterface(abc.ABC):
    """
    Abstract interface for sampler objects.
    """

    @property
    @abc.abstractmethod
    def data(self):
        """
        Sampler data from the configuration file.
        """
        pass

    @abc.abstractmethod
    def check_validity(self):
        """
        Check if the sampler is valid.

        Should validate the input data to ensure that the sampler will
        not produce any errors.
        """
        pass

    @abc.abstractmethod
    def get_samples(self):
        """
        Get samples from the sampler.

        This should return samples as a list of dictionaries, with the
        sample variables as the keys:

        .. code:: python

            [{'b': 0.89856, 'a': 1}, {'b': 0.923223, 'a': 1}, ... ]
        """
        pass

    @property
    @abc.abstractmethod
    def parameters(self):
        """
        Return a of list of the parameters being generated by the
        sampler.
        """
        pass

    @property
    @abc.abstractmethod
    def parameter_block(self):
        """
        Converts samples to parameter dictionary for ``codepy setup`` and ``codepy run``
        """ # noqa
        pass
