# This file is a template, and might need editing before it works on your project.
# Official language image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/python/tags/
image: python:3.6.3

# Change pip's cache directory to be inside the project directory since we can
# only cache local items.
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

stages:
  - build
  - test
  - pages

# Pip's cache doesn't store the python packages
# https://pip.pypa.io/en/stable/reference/pip_install/#caching
#
# If you want to also cache the installed packages, you have to install
# them in a virtualenv and cache it as well.
cache:
  paths:
    - .cache/pip

before_script:
  - python -V  # Print out python version for debugging
  - pip install --upgrade pip
  - pip install -r requirements.txt

test:
  stage: test
  script:
    # an alternative approach is to install and run:
    - pip install dist/*
    # run the command here
    - python setup.py test
    - pip install tox flake8  # you can also use tox
    - cd tests
    - pytest
  tags:
    - docker
  artifacts:
    paths:
      - tests/record.yaml

build:
  stage: build
  script:
    - python setup.py bdist_wheel
  tags:
    - docker
  artifacts:
    paths:
      - dist/*.whl

pages:
  stage: pages
  script:
    - pip install sphinx sphinx-rtd-theme
    - cd docs ; make html
    - mv build/html/ ../public/
  tags:
    - docker
  artifacts:
    paths:
      - public
  only:
    - master
