# run this with codepy run . -c codepy_config_list.yaml

setup:
    interactive: true
    sleep: 1
    autoyes: true
    sampler:
        type: list
        parameters:
            X1: [1, 5, 10]
        constants:
            X2: 5
            X3: 5
