# run this with codepy run . -c codepy_config_uqpipeline.yaml

setup:
  interactive: true
  sleep: 1
  autoyes: true
  sampler:
    type: uqpipeline
    uq_points: points
    uq_variables:
    - X1
    - X2
    uq_code: "points = sampler.CartesianCrossSampler.sample_points(\n    num_divisions=[3,3],\
      \ \n    box=[[-1,1],[]], \n    values=[[],['foo', 'bar']])\n"
